; INFO: You can select or unselect mods by removing or adding a `;` semicolon character on the beginning of the line
; By default, unlimiter and competition patch are enabled
; WARNING: You cannot select both CompetitionPatch and TMInterface! The game will start with black screen and exit immediately.

; The name before the `=` sign doesnt matter, it is only for organisation purposes
[Mods]
CoreMod_1.0.11=CoreMod.dll
TMCompPatch_1.5.3=TMCompPatch.dll
TMUnlimiter_2.0.8=TMUnlimiter.dll
;TMInterface_2.2.0=TMInterface.dll

TMFOXR=TMFOXR.dll
